export enum MacronutrientPreference {
  HighProteinNeeds = 'HighProteinNeeds',
  LowCarbDiet = 'LowCarbDiet',
  BalancedFatIntake = 'BalancedFatIntake',
  IncreasedFiberRequirement = 'IncreasedFiberRequirement',
  LowFatDiet = 'LowFatDiet',
  LowProteinDiet = 'LowProteinDiet',
  HighCarbNeeds = 'HighCarbNeeds',
  ModerateFatIntake = 'ModerateFatIntake',
  HighFiberNeeds = 'HighFiberNeeds',
  LowSugarDiet = 'LowSugarDiet',
}

export const patternCriteria: Record<
  MacronutrientPreference,
  TPatternCriteria
> = {
  [MacronutrientPreference.HighProteinNeeds]: {
    recommendedKeywords: [
      'High protein',
      'Chicken breast',
      'Turkey',
      'Fish',
      'Eggs',
      'Greek yogurt',
      'Tofu',
      'Legumes',
      'Quinoa',
      'Lean beef',
      'Cottage cheese',
      'Pork loin',
      'Edamame',
      'Tempeh',
      'Nuts',
    ],
    avoidedKeywords: [
      'Sugary cereals',
      'White bread',
      'Pastries',
      'Sugary snacks',
      'Excessive refined carbs',
      'Processed meats',
      'Sweetened yogurt',
      'Fried foods',
    ],
  },
  [MacronutrientPreference.LowCarbDiet]: {
    recommendedKeywords: [
      'Low carb',
      'Leafy greens',
      'Avocados',
      'Nuts',
      'Seeds',
      'Meat',
      'Fish',
      'Eggs',
      'Low-carb vegetables',
      'Berries',
      'Cheese',
      'Olives',
      'Coconut oil',
      'Chia seeds',
      'Greek yogurt',
    ],
    avoidedKeywords: [
      'Bread',
      'Pasta',
      'Rice',
      'Potatoes',
      'Sugary foods',
      'Soft drinks',
      'High-carb fruits',
      'Granola bars',
      'Packaged snacks',
    ],
  },
  [MacronutrientPreference.BalancedFatIntake]: {
    recommendedKeywords: [
      'Balanced fat intake',
      'Olive oil',
      'Avocados',
      'Nuts',
      'Fatty fish',
      'Seeds',
      'Coconut oil',
      'Lean meats',
      'Chia seeds',
      'Walnuts',
      'Flaxseeds',
      'Almonds',
      'Dark chocolate',
      'Eggs',
      'Natural peanut butter',
    ],
    avoidedKeywords: [
      'Trans fats',
      'Excessive saturated fats',
      'Processed snacks',
      'Deep-fried foods',
      'Certain margarines',
      'Hydrogenated oils',
      'Fast food',
      'Packaged cookies',
    ],
  },
  [MacronutrientPreference.IncreasedFiberRequirement]: {
    recommendedKeywords: [
      'High fiber',
      'Whole grains',
      'Legumes',
      'Fruits',
      'Vegetables',
      'Nuts',
      'Seeds',
      'Oats',
      'Chia seeds',
      'Barley',
      'Bran',
      'Sweet potatoes',
      'Apples',
      'Pears',
      'Avocados',
    ],
    avoidedKeywords: [
      'Refined grains',
      'Sugary snacks',
      'Processed foods',
      'White bread',
      'Low-fiber foods',
      'Pastries',
      'Candy',
      'Pre-packaged meals',
    ],
  },
  [MacronutrientPreference.LowFatDiet]: {
    recommendedKeywords: [
      'Low fat',
      'Lean meats',
      'Fish',
      'Low-fat dairy products',
      'Fruits',
      'Vegetables',
      'Legumes',
      'Whole grains',
      'Skinless chicken',
      'Turkey',
      'Fat-free yogurt',
      'Beans',
      'Peas',
      'Rice cakes',
      'Low-fat cheese',
    ],
    avoidedKeywords: [
      'Fatty cuts of meat',
      'Full-fat dairy',
      'Fried foods',
      'Pastries',
      'High-fat snacks',
      'Cream',
      'Butter',
      'Oil-rich foods',
    ],
  },
  [MacronutrientPreference.LowProteinDiet]: {
    recommendedKeywords: [
      'Low protein',
      'Vegetables',
      'Fruits',
      'Grains',
      'Nuts',
      'Seeds',
      'Legumes',
      'Low-protein dairy alternatives',
      'Rice',
      'Pasta',
      'Potatoes',
      'Quinoa',
      'Beans',
      'Soy milk',
      'Almond milk',
    ],
    avoidedKeywords: [
      'Red meat',
      'Poultry',
      'Fish',
      'Eggs',
      'High-protein dairy products',
      'Greek yogurt',
      'Protein bars',
      'Nuts',
      'Protein shakes',
    ],
  },
  [MacronutrientPreference.HighCarbNeeds]: {
    recommendedKeywords: [
      'High carb',
      'Whole grains',
      'Fruits',
      'Vegetables',
      'Legumes',
      'Sweet potatoes',
      'Quinoa',
      'Oats',
      'Brown rice',
      'Barley',
      'Whole grain bread',
      'Starchy vegetables',
      'Beans',
      'Lentils',
      'Peas',
    ],
    avoidedKeywords: [
      'Refined sugars',
      'Excessive fat',
      'Highly processed foods',
      'Sugary snacks',
      'Low-carb products',
      'Fried foods',
      'Pastries',
      'Candy',
      'Sugar-sweetened beverages',
    ],
  },
  [MacronutrientPreference.ModerateFatIntake]: {
    recommendedKeywords: [
      'Moderate fat intake',
      'Avocados',
      'Nuts',
      'Olive oil',
      'Fatty fish',
      'Seeds',
      'Lean meats',
      'Low-fat dairy products',
      'Almonds',
      'Flaxseeds',
      'Hemp seeds',
      'Nut butters',
      'Olives',
      'Coconut',
      'Dark chocolate',
    ],
    avoidedKeywords: [
      'Trans fats',
      'Excessive saturated fats',
      'Fried foods',
      'Baked goods with hydrogenated oils',
      'Highly processed snacks',
      'Fast food',
      'Packaged cookies',
      'Creamy sauces',
      'Fatty cuts of meat',
    ],
  },
  [MacronutrientPreference.HighFiberNeeds]: {
    recommendedKeywords: [
      'High fiber',
      'Whole grains',
      'Fruits',
      'Vegetables',
      'Legumes',
      'Nuts',
      'Seeds',
      'Oats',
      'Chia seeds',
      'Bran',
      'Sweet potatoes',
      'Apples',
      'Pears',
      'Berries',
      'Beans',
    ],
    avoidedKeywords: [
      'Refined grains',
      'Sugary snacks',
      'Processed foods',
      'Low-fiber foods',
      'White bread',
      'Pre-packaged meals',
      'Candy',
      'Sugary cereals',
      'Pastries',
    ],
  },
  [MacronutrientPreference.LowSugarDiet]: {
    recommendedKeywords: [
      'Low sugar',
      'Fresh fruits',
      'Vegetables',
      'Whole grains',
      'Lean proteins',
      'Nuts',
      'Seeds',
      'Unsweetened dairy alternatives',
      'Herbal teas',
      'Unsweetened yogurt',
      'Whole grain breads',
      'Fresh herbs',
      'Low-sugar snacks',
      'Beans',
      'Legumes',
    ],
    avoidedKeywords: [
      'Sugary drinks',
      'Candy',
      'Baked goods',
      'Sugary cereals',
      'Processed snacks',
      'Sweetened beverages',
      'Ice cream',
      'Pastries',
      'Sugar-laden condiments',
    ],
  },
};

export type TPatternCriteria = {
  recommendedKeywords: string[];
  avoidedKeywords: string[];
};
