export enum NutrigeneticParameter {
  VitaminCDeficiency = 'VitaminCDeficiency',
  CaffeineSensitivity = 'CaffeineSensitivity',
  GlutenIntolerance = 'GlutenIntolerance',
  LactoseIntolerance = 'LactoseIntolerance',
  IronAbsorption = 'IronAbsorption',
  Omega3Metabolism = 'Omega3Metabolism',
  VitaminDDeficiency = 'VitaminDDeficiency',
  SaltSensitivity = 'SaltSensitivity',
  FolicAcidMetabolism = 'FolicAcidMetabolism',
  CarbSensitivity = 'CarbSensitivity',
  FatMetabolism = 'FatMetabolism',
  HistamineIntolerance = 'HistamineIntolerance',
}

export const patternCriteria: Record<NutrigeneticParameter, TPatternCriteria> =
  {
    [NutrigeneticParameter.VitaminCDeficiency]: {
      recommendedFoods: [
        'Oranges',
        'Strawberries',
        'Red peppers',
        'Broccoli',
        'Kiwi',
        'Brussels sprouts',
        'Tomatoes',
        'Kale',
      ],
      avoidedFoods: [
        'White bread',
        'Cakes',
        'Cookies',
        'Sugary drinks',
        'Chips',
        'Processed meats',
        'High-sugar foods',
      ],
    },
    [NutrigeneticParameter.CaffeineSensitivity]: {
      recommendedFoods: [
        'Caffeine-free beverages',
        'Herbal teas',
        'Decaffeinated coffee',
        'Coconut water',
        'Fruit juices',
      ],
      avoidedFoods: [
        'Coffee',
        'Tea',
        'Chocolate',
        'Energy drinks',
        'Certain sodas',
        'Pre-workout supplements',
        'Caffeine',
      ],
    },
    [NutrigeneticParameter.GlutenIntolerance]: {
      recommendedFoods: [
        'Rice',
        'Corn',
        'Potatoes',
        'Fresh fruits and vegetables',
        'Quinoa',
        'Buckwheat',
        'Gluten-free oats',
        'Legumes',
      ],
      avoidedFoods: [
        'Wheat breads',
        'Pasta',
        'Beer',
        'Oats',
        'Processed foods with gluten',
        'Certain sauces and dressings',
        'Gluten',
      ],
    },
    [NutrigeneticParameter.LactoseIntolerance]: {
      recommendedFoods: [
        'Lactose-free dairy products',
        'Leafy greens',
        'Nuts',
        'Fortified plant-based milks',
        'Yogurt alternatives',
        'Almond milk',
        'Coconut milk',
      ],
      avoidedFoods: [
        'Milk',
        'Cheese',
        'Yogurt',
        'Ice cream',
        'Butter',
        'Certain baked goods',
        'Lactose',
      ],
    },
    [NutrigeneticParameter.IronAbsorption]: {
      recommendedFoods: [
        'Red meat',
        'Spinach',
        'Legumes',
        'Fortified cereals',
        'Pumpkin seeds',
        'Quinoa',
        'Tofu',
        'Lentils',
      ],
      avoidedFoods: [
        'Coffee',
        'Tea',
        'Calcium-rich foods',
        'Excessive dairy',
        'Soy milk with added calcium',
        'Phytates',
      ],
    },
    [NutrigeneticParameter.Omega3Metabolism]: {
      recommendedFoods: [
        'Fatty fish',
        'Chia seeds',
        'Flaxseeds',
        'Walnuts',
        'Hemp seeds',
        'Seaweed',
        'Edamame',
        'Brussels sprouts',
      ],
      avoidedFoods: [
        'Processed meats',
        'Excessive omega-6 oils',
        'Fried foods',
        'Certain vegetable oils',
        'Packaged snacks',
        'Trans fats',
      ],
    },
    [NutrigeneticParameter.VitaminDDeficiency]: {
      recommendedFoods: [
        'Fatty fish',
        'Fortified dairy products',
        'Egg yolks',
        'Mushrooms',
        'Fortified orange juice',
        'Cod liver oil',
        'Cheese',
      ],
      avoidedFoods: [
        'Low-fat dairy products',
        'Certain vegetable oils',
        'Highly processed foods',
        'Sugary cereals',
        'Phytic acid',
      ],
    },
    [NutrigeneticParameter.SaltSensitivity]: {
      recommendedFoods: [
        'Fresh fruits and vegetables',
        'Herbs and spices',
        'Low-sodium foods',
        'Fresh poultry',
        'Whole grains',
        'Unsalted nuts',
      ],
      avoidedFoods: [
        'Salty snacks',
        'Processed foods',
        'Canned soups',
        'Fast food',
        'Pre-packaged meals',
        'Sodium',
      ],
    },
    [NutrigeneticParameter.FolicAcidMetabolism]: {
      recommendedFoods: [
        'Leafy greens',
        'Legumes',
        'Fortified cereals',
        'Nuts',
        'Beets',
        'Avocados',
        'Asparagus',
      ],
      avoidedFoods: [
        'Excessive alcohol',
        'Certain medications',
        'Highly processed foods',
        'Sugary snacks',
        'Synthetic folic acid',
      ],
    },
    [NutrigeneticParameter.CarbSensitivity]: {
      recommendedFoods: [
        'Whole grains',
        'Vegetables',
        'Lean proteins',
        'Healthy fats',
        'Sweet potatoes',
        'Legumes',
        'Quinoa',
      ],
      avoidedFoods: [
        'Refined sugars',
        'White bread',
        'Pastries',
        'Sugary drinks',
        'White rice',
        'Processed snacks',
        'Simple carbohydrates',
      ],
    },
    [NutrigeneticParameter.FatMetabolism]: {
      recommendedFoods: [
        'Avocados',
        'Nuts',
        'Olive oil',
        'Fatty fish',
        'Chia seeds',
        'Flaxseeds',
        'Coconut oil',
      ],
      avoidedFoods: [
        'Trans fats',
        'Excessive saturated fats',
        'Fried foods',
        'Baked goods with hydrogenated oils',
        'Certain margarine',
        'High-cholesterol foods',
      ],
    },
    [NutrigeneticParameter.HistamineIntolerance]: {
      recommendedFoods: [
        'Fresh meats',
        'Gluten-free grains',
        'Fresh fruits and vegetables',
        'Rice',
        'Coconut products',
        'Eggs',
      ],
      avoidedFoods: [
        'Aged cheeses',
        'Fermented foods',
        'Processed meats',
        'Certain wines',
        'Pickled foods',
        'Vinegar-based products',
        'Histamine-rich foods',
      ],
    },
  };

export type TPatternCriteria = {
  recommendedFoods: string[];
  avoidedFoods: string[];
};
