export enum NutrigeneticParameter {
  VitaminCDeficiency = 'VitaminCDeficiency',
  CaffeineSensitivity = 'CaffeineSensitivity',
  GlutenIntolerance = 'GlutenIntolerance',
  LactoseIntolerance = 'LactoseIntolerance',
  IronAbsorption = 'IronAbsorption',
  Omega3Metabolism = 'Omega3Metabolism',
  VitaminDDeficiency = 'VitaminDDeficiency',
  SaltSensitivity = 'SaltSensitivity',
  FolicAcidMetabolism = 'FolicAcidMetabolism',
  CarbSensitivity = 'CarbSensitivity',
  FatMetabolism = 'FatMetabolism',
  HistamineIntolerance = 'HistamineIntolerance',
}

export const patternCriteria: Record<NutrigeneticParameter, TPatternCriteria> =
  {
    [NutrigeneticParameter.VitaminCDeficiency]: {
      recommendedFoods: [
        'Oranges',
        'Strawberries',
        'Red peppers',
        'Broccoli',
        'Kiwi',
        'Brussels sprouts',
        'Tomatoes',
        'Kale',
        'Grapefruits',
        'Mangoes',
        'Papayas',
        'Cantaloupe',
        'Pineapples',
        'Guavas',
        'Chili peppers',
      ],
      avoidedFoods: [
        'White bread',
        'Cakes',
        'Cookies',
        'Sugary drinks',
        'Chips',
        'Processed meats',
        'High-sugar foods',
        'Pastries',
        'Fried foods',
        'Canned foods',
        'Sugary cereals',
        'Processed snacks',
        'Pre-packaged meals',
      ],
    },
    [NutrigeneticParameter.CaffeineSensitivity]: {
      recommendedFoods: [
        'Caffeine-free beverages',
        'Herbal teas',
        'Decaffeinated coffee',
        'Coconut water',
        'Fruit juices',
        'Herbal infusions',
        'Non-caffeinated sodas',
        'Warm milk',
        'Ginger tea',
        'Mint tea',
        'Fruit smoothies',
        'Cucumber water',
        'Aloe vera juice',
      ],
      avoidedFoods: [
        'Coffee',
        'Tea',
        'Chocolate',
        'Energy drinks',
        'Certain sodas',
        'Pre-workout supplements',
        'Caffeine',
        'High-caffeine energy drinks',
        'Cola drinks',
        'Iced tea',
        'Certain diet sodas',
        'Caffeinated gum',
      ],
    },
    [NutrigeneticParameter.GlutenIntolerance]: {
      recommendedFoods: [
        'Rice',
        'Corn',
        'Potatoes',
        'Fresh fruits and vegetables',
        'Quinoa',
        'Buckwheat',
        'Gluten-free oats',
        'Legumes',
        'Amaranth',
        'Chia seeds',
        'Millet',
        'Tapioca',
        'Polenta',
        'Arrowroot',
        'Almond flour',
      ],
      avoidedFoods: [
        'Wheat breads',
        'Pasta',
        'Beer',
        'Oats',
        'Processed foods with gluten',
        'Certain sauces and dressings',
        'Gluten',
        'Certain baked goods',
        'Breaded foods',
        'Certain cereals',
        'Barley',
        'Rye',
        'Seitan',
      ],
    },
    [NutrigeneticParameter.LactoseIntolerance]: {
      recommendedFoods: [
        'Lactose-free dairy products',
        'Leafy greens',
        'Nuts',
        'Fortified plant-based milks',
        'Yogurt alternatives',
        'Almond milk',
        'Coconut milk',
        'Rice milk',
        'Soy milk',
        'Cashew milk',
        'Hemp milk',
        'Lactase enzyme supplements',
        'Fruits',
        'Vegetables',
        'Legumes',
      ],
      avoidedFoods: [
        'Milk',
        'Cheese',
        'Yogurt',
        'Ice cream',
        'Butter',
        'Certain baked goods',
        'Lactose',
        'Cream',
        'Whey protein',
        'Certain processed foods',
        'Milk chocolate',
        'Cheesecakes',
        'Lactose-containing medications',
      ],
    },
    [NutrigeneticParameter.IronAbsorption]: {
      recommendedFoods: [
        'Red meat',
        'Spinach',
        'Legumes',
        'Fortified cereals',
        'Pumpkin seeds',
        'Quinoa',
        'Tofu',
        'Lentils',
        'Chickpeas',
        'Beef liver',
        'Sesame seeds',
        'Dark chocolate',
        'Shellfish',
        'Turkey',
        'Poultry',
      ],
      avoidedFoods: [
        'Coffee',
        'Tea',
        'Calcium-rich foods',
        'Excessive dairy',
        'Soy milk with added calcium',
        'Phytates',
        'High-calcium supplements',
        'Certain whole grains',
        'Calcium-fortified juices',
        'Excessive fiber',
        'Certain vegetables',
        'Calcium-rich leafy greens',
      ],
    },
    [NutrigeneticParameter.Omega3Metabolism]: {
      recommendedFoods: [
        'Fatty fish',
        'Chia seeds',
        'Flaxseeds',
        'Walnuts',
        'Hemp seeds',
        'Seaweed',
        'Edamame',
        'Brussels sprouts',
        'Algal oil',
        'Salmon',
        'Sardines',
        'Mackerel',
        'Herring',
        'Anchovies',
        'Cod liver oil',
      ],
      avoidedFoods: [
        'Processed meats',
        'Excessive omega-6 oils',
        'Fried foods',
        'Certain vegetable oils',
        'Packaged snacks',
        'Trans fats',
        'Certain margarines',
        'High-omega-6 oils',
        'Certain fast foods',
        'Commercial baked goods',
        'Pre-packaged snacks',
        'Certain salad dressings',
      ],
    },
    [NutrigeneticParameter.VitaminDDeficiency]: {
      recommendedFoods: [
        'Fatty fish',
        'Fortified dairy products',
        'Egg yolks',
        'Mushrooms',
        'Fortified orange juice',
        'Cod liver oil',
        'Cheese',
        'Fortified plant-based milks',
        'Beef liver',
        'Fortified cereals',
        'Canned salmon',
        'Sardines',
        'Sunflower seeds',
        'Fortified margarine',
        'Eggs',
      ],
      avoidedFoods: [
        'Low-fat dairy products',
        'Certain vegetable oils',
        'Highly processed foods',
        'Sugary cereals',
        'Phytic acid',
        'Certain baked goods',
        'High-sugar foods',
        'Certain beverages with added sugars',
        'Certain processed cheeses',
        'Certain candies',
        'Excessive alcohol',
        'Refined grains',
      ],
    },
    [NutrigeneticParameter.SaltSensitivity]: {
      recommendedFoods: [
        'Fresh fruits and vegetables',
        'Herbs and spices',
        'Low-sodium foods',
        'Fresh poultry',
        'Whole grains',
        'Unsalted nuts',
        'Fresh fish',
        'Lean meats',
        'Natural yogurt',
        'Fresh herbs',
        'Vegetable soups',
        'Unsalted seeds',
        'Plain rice',
        'Herbal teas',
        'Whole grain bread',
      ],
      avoidedFoods: [
        'Salty snacks',
        'Processed foods',
        'Canned soups',
        'Fast food',
        'Pre-packaged meals',
        'Sodium',
        'Certain sauces',
        'Pickled foods',
        'Certain cheeses',
        'Salted nuts',
        'Salted meats',
        'Certain frozen meals',
        'Certain convenience foods',
      ],
    },
    [NutrigeneticParameter.FolicAcidMetabolism]: {
      recommendedFoods: [
        'Leafy greens',
        'Legumes',
        'Fortified cereals',
        'Nuts',
        'Beets',
        'Avocados',
        'Asparagus',
        'Broccoli',
        'Brussels sprouts',
        'Sunflower seeds',
        'Peas',
        'Lentils',
        'Chickpeas',
        'Oranges',
        'Whole grains',
      ],
      avoidedFoods: [
        'Excessive alcohol',
        'Certain medications',
        'Highly processed foods',
        'Sugary snacks',
        'Synthetic folic acid',
        'Certain soft drinks',
        'Certain candies',
        'Highly processed meats',
        'Certain sauces',
        'Refined grains',
        'Certain fast foods',
      ],
    },
    [NutrigeneticParameter.CarbSensitivity]: {
      recommendedFoods: [
        'Whole grains',
        'Vegetables',
        'Lean proteins',
        'Healthy fats',
        'Sweet potatoes',
        'Legumes',
        'Quinoa',
        'Brown rice',
        'Oats',
        'Barley',
        'Millet',
        'Chia seeds',
        'Non-starchy vegetables',
        'Berries',
        'Nuts',
      ],
      avoidedFoods: [
        'Refined sugars',
        'White bread',
        'Pastries',
        'Sugary drinks',
        'White rice',
        'Processed snacks',
        'Simple carbohydrates',
        'Candy',
        'Sugary cereals',
        'Certain baked goods',
        'Certain fast foods',
        'Sugary condiments',
      ],
    },
    [NutrigeneticParameter.FatMetabolism]: {
      recommendedFoods: [
        'Avocados',
        'Nuts',
        'Olive oil',
        'Fatty fish',
        'Chia seeds',
        'Flaxseeds',
        'Coconut oil',
        'Almonds',
        'Walnuts',
        'Pumpkin seeds',
        'Hemp seeds',
        'Seafood',
        'Natural peanut butter',
        'Nut butters',
        'Lean poultry',
      ],
      avoidedFoods: [
        'Trans fats',
        'Excessive saturated fats',
        'Fried foods',
        'Baked goods with hydrogenated oils',
        'Certain margarine',
        'High-cholesterol foods',
        'Certain packaged snacks',
        'Certain fast foods',
        'Certain pre-packaged meals',
        'Certain restaurant foods',
        'Certain microwave meals',
      ],
    },
    [NutrigeneticParameter.HistamineIntolerance]: {
      recommendedFoods: [
        'Fresh meats',
        'Gluten-free grains',
        'Fresh fruits and vegetables',
        'Rice',
        'Coconut products',
        'Eggs',
        'Fresh herbs',
        'Organic meats',
        'Fresh fish',
        'Homemade soups',
        'Non-aged cheeses',
        'Freshly prepared foods',
        'Low-histamine vegetables',
        'Fresh fruit juices',
        'Fresh herbs',
      ],
      avoidedFoods: [
        'Aged cheeses',
        'Fermented foods',
        'Processed meats',
        'Certain wines',
        'Pickled foods',
        'Vinegar-based products',
        'Histamine-rich foods',
        'Certain sauces',
        'Certain condiments',
        'Certain processed snacks',
        'Certain ready-made meals',
      ],
    },
  };

export type TPatternCriteria = {
  recommendedFoods: string[];
  avoidedFoods: string[];
};
