name: CI Workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

jobs:
  MSDO:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            5.0.x
            6.0.x
      - name: Run Microsoft Security DevOps
        uses: microsoft/security-devops-action@v1.6.0
        id: msdo
      - name: Upload results to Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.msdo.outputs.sarifFile }}
  run-tests:
    env:
      PORT: 3000
      DB_HOST: localhost
      DB_PORT: 3306
      DB_USERNAME: test
      DB_PASSWORD: test
      DB_NAME: test
      SONAR_SERVER_URL: test
      SONAR_TOKEN: test
      AWS_COGNITO_USER_POOL_ID: INVALID_USER_POOL_ID
      AWS_COGNITO_CLIENT_ID: INVALID_CLIENT_ID
      AWS_COGNITO_AUTHORITY: INVALID_AUTHORITY
      AWS_COGNITO_ENDPOINT: INVALID_ENDPOINT

    name: Run tests
    needs: MSDO
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build
        run: |
          pnpm run lint
          pnpm run format
          pnpm run build
          pnpm run test
